pool:
  vmImage: windows-latest

trigger:
  paths:
    include:
    # Only trigger on update of `current.zip`
    - current.zip

resources:
  repositories:
    - repository: dumped-cs
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-dumped-cs

variables:
  - template: variables/main.yml

stages:
- stage: DumpCS
  jobs:
    - job: DumpCS
      displayName: Dump C#
      steps:
        - template: templates/setup.yml

        - task: ExtractFiles@1
          displayName: 'Extract Binary ZIP'
          inputs:
            archiveFilePatterns: $(REPO_APK_DUMPER_ABS_DIR)/current.zip
            destinationFolder: $(REPO_APK_DUMPER_ABS_DIR)
            cleanDestinationFolder: false

        - powershell: |
            .\.tool\Il2CppDumper-6.7.40\Il2CppDumper.exe `
              .\libil2cpp.so `
              .\global-metadata.dat `
              $(CPP_DUMP_OUTPUT_DIR)
            # For ignoring the error from `Il2CppDumper.exe`, because it reads the console at the end of decompiling,
            # but there's no console interaction in CI.
            Write-Host "##vso[task.complete result=Succeeded;]"
            Exit
          displayName: 'Dump DLLs'
          workingDirectory: $(REPO_APK_DUMPER_ABS_DIR)

        - powershell: |
            ilspycmd `
              -o $(DUMPED_CS_DIR) `
              -p `
              .\$(CPP_DUMP_OUTPUT_DIR)\DummyDll\PSMain.dll
          displayName: 'Convert DLLs to C#'
          workingDirectory: $(REPO_APK_DUMPER_ABS_DIR)

        - task: PowerShell@2
          displayName: Commit C# Dump Changes
          inputs:
            targetType: 'inline'
            script: |
              $Version = $(Get-Content -Path "$(REPO_APK_DUMPER_ABS_DIR)\current-version.txt")
              git checkout main
              git add .
              git commit -m "Updated C# dumps to $Version by $(Build.Repository.Name)@$(Build.SourceVersion)" || echo "No changes to commit"
              git push origin main
            workingDirectory: $(REPO_DUMPED_CS_ABS_DIR)
            pwsh: true
